### ISSUE TITLE
Feature request: integration into TYPO3 CMS 11

### ISSUE THREAD

**Issue by h3nn3s** [mailjet/typo3-mailjet-module-apiv3#33]
Hi,
we want to use Mailjet integration with TYPO3 CMS v11 LTS.
Our client wants to migrate to Mailjet - this depends on a working Integration.

Any plans, when to raise compatibility?

Kind regards,
Henrik

**Comment by h3nn3s** [comment]
are PRs welcommed? Whats your plan?

**Comment by oleksandr-mykhailenko** [comment]
Hello @h3nn3s 
We have this item in progress and working on that
Soon we will have updates
Thank you

**Comment by oleksandr-mykhailenko** [comment]
This one was resolved
